'use client';

import { useEffect, useMemo, useState } from 'react';

type ActivityType = '러닝'|'걷기'|'자전거'|'등산'|'수영'|'기타';
type Activity = {
 id:string; date:string; type:ActivityType; distanceKm:number; durationSec:number;
 calories?:number; steps?:number; avgPaceSecPerKm?:number; bestPaceSecPerKm?:number; avgSpeedKmh?:number; bestSpeedKmh?:number;
 elevationGainM?:number; elevationLossM?:number; avgHeartRate?:number; maxHeartRate?:number; avgCadence?:number; maxCadence?:number; vo2max?:number;
 note?:string; source?:string; deletedAt?:string;
};

type Tab='home'|'records'|'analysis'|'trash'|'more';
const STORAGE='motion-log-records-v4'; const THEME='motion-log-theme-v4';
const empty:Activity[]=[];
const fmtDate=(d:string)=>{const x=new Date(`${d}T00:00:00`);return `${x.getMonth()+1}월 ${x.getDate()}일`};
const fmtFullDate=(d:string)=>{const x=new Date(`${d}T00:00:00`);return `${x.getFullYear()}.${String(x.getMonth()+1).padStart(2,'0')}.${String(x.getDate()).padStart(2,'0')}`};
const fmtDur=(s=0)=>{const n=Math.max(0,Math.round(s));const h=Math.floor(n/3600),m=Math.floor(n%3600/60),r=n%60;return h?`${h}시간 ${m}분`:`${m}분 ${String(r).padStart(2,'0')}초`};
const fmtPace=(s?:number)=>s&&Number.isFinite(s)?`${Math.floor(s/60)}'${String(Math.round(s%60)).padStart(2,'0')}"/km`:'—';
const avg=(v:number[])=>{const a=v.filter(Number.isFinite);return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0};
const sum=(a:Activity[],k:'distanceKm'|'durationSec'|'calories')=>a.reduce((s,x)=>s+(Number(x[k])||0),0);
function Metric({label,value,unit}:{label:string;value:string|number;unit?:string}){return <div className="metric"><span>{label}</span><strong>{value}{unit&&<small>{unit}</small>}</strong></div>}
function RecordCard({a,onOpen,onTrash}:{a:Activity;onOpen:()=>void;onTrash:()=>void}){return <article className="record-card" onClick={onOpen}><div><div className="record-date"><b>{fmtDate(a.date)}</b><span>{a.type}</span></div><div className="record-main"><b>{a.distanceKm.toFixed(2)}<small> km</small></b><span>{fmtDur(a.durationSec)} · {fmtPace(a.avgPaceSecPerKm)}</span></div></div><div className="record-tags">{a.avgHeartRate&&<span>♥ {Math.round(a.avgHeartRate)}</span>}{a.avgCadence&&<span>↟ {Math.round(a.avgCadence)}</span>}{a.calories&&<span>{Math.round(a.calories)} kcal</span>}{a.vo2max&&<span>VO₂ {a.vo2max}</span>}</div><button className="icon-button" onClick={e=>{e.stopPropagation();onTrash()}}>×</button></article>}

export default function Home(){
 const [tab,setTab]=useState<Tab>('home'); const [acts,setActs]=useState<Activity[]>(empty); const [selected,setSelected]=useState<Activity|null>(null);
 const [confirm,setConfirm]=useState<{kind:'trash'|'restore'|'delete';id:string}|null>(null); const [dark,setDark]=useState(false); const [period,setPeriod]=useState<7|30|90|365>(30);
 const [query,setQuery]=useState(''); const [typeFilter,setTypeFilter]=useState<'전체'|ActivityType>('전체'); const [sort,setSort]=useState<'latest'|'distance'|'pace'>('latest');
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);setActs(raw?JSON.parse(raw):[]);const t=localStorage.getItem(THEME);if(t)setDark(t==='dark')}catch{setActs([])}},[]);
 useEffect(()=>{localStorage.setItem(STORAGE,JSON.stringify(acts));localStorage.setItem(THEME,dark?'dark':'light')},[acts,dark]);
 const active=useMemo(()=>acts.filter(a=>!a.deletedAt).sort((a,b)=>b.date.localeCompare(a.date)),[acts]); const trash=acts.filter(a=>a.deletedAt); const latest=active[0];
 const today=new Date(); const year=today.getFullYear(); const yearActivities=active.filter(a=>a.date.startsWith(String(year)));
 const week=active.filter(a=>{const d=new Date();d.setDate(d.getDate()-6);return a.date>=d.toISOString().slice(0,10)});
 const since=useMemo(()=>{const d=new Date();d.setDate(d.getDate()-(period-1));return d.toISOString().slice(0,10)},[period]); const scoped=active.filter(a=>a.date>=since);
 const filtered=useMemo(()=>active.filter(a=>(typeFilter==='전체'||a.type===typeFilter)&&(query.trim()===''||a.type.includes(query.trim())||fmtFullDate(a.date).includes(query.trim())||String(a.note||'').includes(query.trim()))).sort((a,b)=>sort==='distance'?b.distanceKm-a.distanceKm:sort==='pace'?(a.avgPaceSecPerKm||99999)-(b.avgPaceSecPerKm||99999):b.date.localeCompare(a.date)),[active,typeFilter,query,sort]);
 const allDist=sum(active,'distanceKm'), weekDist=sum(week,'distanceKm'), yearDist=sum(yearActivities,'distanceKm');
 const runs=active.filter(a=>a.type==='러닝'); const runPBpace=runs.filter(a=>a.distanceKm>=1).sort((a,b)=>(a.avgPaceSecPerKm||99999)-(b.avgPaceSecPerKm||99999))[0]; const longestRun=runs.slice().sort((a,b)=>b.distanceKm-a.distanceKm)[0];
 const maxSpeedRun=runs.slice().sort((a,b)=>(b.avgSpeedKmh||0)-(a.avgSpeedKmh||0))[0];
 const monthly=Array.from({length:12},(_,i)=>({m:i+1,n:yearActivities.filter(a=>new Date(a.date+'T00:00:00').getMonth()===i).length,d:yearActivities.filter(a=>new Date(a.date+'T00:00:00').getMonth()===i).reduce((s,a)=>s+a.distanceKm,0)}));
 const applyConfirm=()=>{if(!confirm)return;setActs(prev=>confirm.kind==='delete'?prev.filter(a=>a.id!==confirm.id):prev.map(a=>a.id===confirm.id?(confirm.kind==='trash'?{...a,deletedAt:new Date().toISOString()}:{...a,deletedAt:undefined}):a));setSelected(null);setConfirm(null)};
 const title=tab==='home'?'운동 대시보드':tab==='records'?'운동 기록':tab==='analysis'?'분석':tab==='trash'?'휴지통':'설정';
 const exportJson=()=>{const b=new Blob([JSON.stringify(acts,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`motion-log-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u)};
 const exportCsv=()=>{const cols=['date','type','distanceKm','durationSec','calories','avgPaceSecPerKm','bestPaceSecPerKm','avgSpeedKmh','bestSpeedKmh','avgHeartRate','maxHeartRate','avgCadence','maxCadence','vo2max','elevationGainM','elevationLossM','steps'];const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;const body=[cols.join(','),...active.map(a=>cols.map(c=>esc((a as any)[c])).join(','))].join('\n');const b=new Blob(['\ufeff'+body],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`motion-log-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(u)};
 return <main className={dark?'app dark':'app'}>
  <aside className="sidebar"><div className="brand"><span>MOTION</span> LOG</div><div className="brand-sub">GALAXY WATCH FITNESS ARCHIVE</div><nav>{[['home','대시보드'],['records','운동 기록'],['analysis','분석'],['trash',`휴지통${trash.length?` (${trash.length})`:''}`],['more','설정']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as Tab)}>{l}</button>)}</nav><div className="sidebar-foot"><button className="ghost" onClick={()=>setDark(v=>!v)}>{dark?'☼ 라이트 모드':'◐ 다크 모드'}</button><small>Samsung Health → Motion Log</small></div></aside>
  <section className="content"><header className="topbar"><div><div className="eyebrow">MOTION LOG</div><h1>{title}</h1></div><div className="status-pill">{active.length.toLocaleString()} RECORDS</div></header>
   {tab==='home'&&<><section className="hero"><div><div className="eyebrow">LATEST ACTIVITY</div>{latest?<><h2>{latest.type} <span>{latest.distanceKm.toFixed(2)} km</span></h2><p>{fmtFullDate(latest.date)} · {fmtDur(latest.durationSec)} · {fmtPace(latest.avgPaceSecPerKm)}{latest.avgHeartRate?` · 평균 ${Math.round(latest.avgHeartRate)} bpm`:''}</p></>:<><h2>기록을 불러오세요.</h2><p>설정에서 Motion Log JSON 백업을 불러오면 전체 운동 이력이 표시됩니다.</p></>}</div><div className="workflow"><span>01</span><b>Samsung Health</b><span>02</span><b>기록 정리</b><span>03</span><b>Motion Log</b></div></section>
    <section className="stats-grid"><Metric label="이번 주 운동" value={week.length} unit="회"/><Metric label="이번 주 거리" value={weekDist.toFixed(1)} unit="km"/><Metric label={`${year}년 거리`} value={yearDist.toFixed(1)} unit="km"/><Metric label="누적 거리" value={allDist.toFixed(1)} unit="km"/><Metric label="최장 러닝" value={longestRun?longestRun.distanceKm.toFixed(2):'—'} unit={longestRun?'km':undefined}/><Metric label="러닝 평균 최고속" value={maxSpeedRun?maxSpeedRun.avgSpeedKmh?.toFixed(1):'—'} unit={maxSpeedRun?'km/h':undefined}/></section>
    <section className="analysis-grid"><div className="panel"><div className="eyebrow">RUNNING PB SNAPSHOT</div><h3>러닝 핵심 기록</h3><div className="mini-grid" style={{marginTop:12}}><div><span>1km 이상 평균 페이스 최고</span><b>{runPBpace?fmtPace(runPBpace.avgPaceSecPerKm):'—'}</b></div><div><span>최장 러닝</span><b>{longestRun?`${longestRun.distanceKm.toFixed(2)} km`: '—'}</b></div><div><span>평균 심박 최저</span><b>{runs.length?`${Math.min(...runs.filter(a=>a.avgHeartRate).map(a=>a.avgHeartRate!))} bpm`:'—'}</b></div><div><span>VO₂ Max 최신</span><b>{[...runs].reverse().find(a=>a.vo2max)?.vo2max??'—'}</b></div></div></div><div className="panel"><div className="eyebrow">YEAR AT A GLANCE</div><h3>{year} 월별 운동량</h3><div className="bar-list" style={{marginTop:12}}>{monthly.map(x=><div key={x.m}><span>{x.m}월</span><i><em style={{width:`${yearDist?Math.min(100,(x.d/Math.max(...monthly.map(y=>y.d),1))*100):0}%`}}/></i><b>{x.d.toFixed(1)}</b></div>)}</div></div></section>
    <div className="section-head"><div><div className="eyebrow">RECENT</div><h3>최근 운동</h3></div><button className="text-btn" onClick={()=>setTab('records')}>전체 보기 →</button></div><div className="records-list">{active.slice(0,8).map(a=><RecordCard key={a.id} a={a} onOpen={()=>setSelected(a)} onTrash={()=>setConfirm({kind:'trash',id:a.id})}/>)}</div></>}
   {tab==='records'&&<><div className="section-head"><div><div className="eyebrow">ARCHIVE</div><h3>운동 기록</h3></div><span className="count-pill">총 {active.length.toLocaleString()}회 · {allDist.toFixed(1)} km</span></div><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8,marginBottom:10}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="날짜·운동종류·메모 검색" style={{width:'100%',padding:'11px 12px',border:'1px solid var(--line)',borderRadius:11,background:'var(--surface)',color:'var(--text)',outline:'none'}}/><select value={sort} onChange={e=>setSort(e.target.value as any)} style={{padding:'0 10px',border:'1px solid var(--line)',borderRadius:11,background:'var(--surface)',color:'var(--text)'}}><option value="latest">최신순</option><option value="distance">거리순</option><option value="pace">페이스순</option></select></div><div className="period-tabs">{(['전체','러닝','걷기','자전거','등산','수영','기타'] as const).map(t=><button key={t} className={typeFilter===t?'active':''} onClick={()=>setTypeFilter(t)}>{t}</button>)}</div><div className="records-list">{filtered.map(a=><RecordCard key={a.id} a={a} onOpen={()=>setSelected(a)} onTrash={()=>setConfirm({kind:'trash',id:a.id})}/>)}</div>{!filtered.length&&<div className="empty">조건에 맞는 기록이 없습니다.</div>}</>}
   {tab==='analysis'&&<><div className="period-tabs">{([7,30,90,365] as const).map(p=><button key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p===365?'1년':`${p}일`}</button>)}</div><section className="stats-grid"><Metric label="기간 운동" value={scoped.length} unit="회"/><Metric label="기간 거리" value={sum(scoped,'distanceKm').toFixed(1)} unit="km"/><Metric label="기간 시간" value={fmtDur(sum(scoped,'durationSec'))}/><Metric label="평균 심박" value={avg(scoped.map(a=>a.avgHeartRate||NaN))||'—'} unit={avg(scoped.map(a=>a.avgHeartRate||NaN))?'bpm':undefined}/><Metric label="평균 케이던스" value={avg(scoped.map(a=>a.avgCadence||NaN))||'—'} unit={avg(scoped.map(a=>a.avgCadence||NaN))?'spm':undefined}/><Metric label="칼로리" value={Math.round(sum(scoped,'calories')).toLocaleString()} unit="kcal"/></section><section className="analysis-grid"><div className="panel"><div className="eyebrow">ACTIVITY MIX</div><h3>종목별 기록</h3><div className="mini-grid" style={{marginTop:12}}>{(['러닝','걷기','자전거','등산','수영','기타'] as ActivityType[]).map(t=><div key={t}><span>{t}</span><b>{scoped.filter(a=>a.type===t).length}회 · {scoped.filter(a=>a.type===t).reduce((s,a)=>s+a.distanceKm,0).toFixed(1)} km</b></div>)}</div></div><div className="panel"><div className="eyebrow">RECENT PERFORMANCE</div><h3>기간 내 러닝</h3><div className="bar-list" style={{marginTop:12}}>{scoped.filter(a=>a.type==='러닝').slice(0,10).map(a=><div key={a.id}><span>{fmtDate(a.date)}</span><i><em style={{width:`${Math.max(6,Math.min(100,(a.distanceKm/10)*100))}%`}}/></i><b>{fmtPace(a.avgPaceSecPerKm)}</b></div>)}</div></div></section></>}
   {tab==='trash'&&<><div className="trash-note">삭제한 기록을 복원하거나 영구 삭제할 수 있습니다.</div><div className="records-list">{trash.map(a=><article className="trash-card" key={a.id}><div><b>{fmtDate(a.date)} · {a.type}</b><span>{a.distanceKm.toFixed(2)} km · {fmtDur(a.durationSec)}</span></div><div><button className="secondary" onClick={()=>setConfirm({kind:'restore',id:a.id})}>복원</button><button className="danger" onClick={()=>setConfirm({kind:'delete',id:a.id})}>영구 삭제</button></div></article>)}</div>{!trash.length&&<div className="empty">휴지통이 비어 있습니다.</div>}</>}
   {tab==='more'&&<><section className="panel settings-panel"><div className="eyebrow">IMPORT</div><h3>삼성헬스 운동 기록 불러오기</h3><p>Motion Log용 JSON 백업을 선택하면 현재 브라우저 기록을 한 번에 교체합니다. ZIP 원본은 이 화면에서 직접 저장하지 않습니다.</p><div className="actions"><label className="secondary file-btn">JSON 불러오기<input type="file" accept="application/json" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result));if(!Array.isArray(p))throw new Error();setActs(p);alert(`${p.length.toLocaleString()}건을 불러왔습니다.`)}catch{alert('올바른 Motion Log JSON 파일이 아닙니다.')}};r.readAsText(f)}}/></label></div></section><section className="panel settings-panel"><div className="eyebrow">BACKUP</div><h3>데이터 백업</h3><p>JSON은 원상 복구용, CSV는 엑셀/분석용으로 사용할 수 있습니다.</p><div className="actions"><button className="secondary" onClick={exportJson}>JSON 내보내기</button><button className="secondary" onClick={exportCsv}>CSV 내보내기</button></div></section><section className="panel settings-panel"><div className="eyebrow">MAINTENANCE</div><h3>화면 테마</h3><button className="secondary" onClick={()=>setDark(v=>!v)}>{dark?'라이트 모드로 전환':'다크 모드로 전환'}</button></section></>}
  </section>
  <nav className="bottom-nav">{[['home','⌂','홈'],['records','▤','기록'],['analysis','⌁','분석'],['trash','♜','휴지통'],['more','⋯','설정']].map(([k,i,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as Tab)}><span>{i}</span><small>{l}</small></button>)}</nav>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">ACTIVITY DETAIL</div><h2>{selected.type} · {selected.distanceKm.toFixed(2)} km</h2><p>{fmtFullDate(selected.date)} · {fmtDur(selected.durationSec)}</p></div><button className="close" onClick={()=>setSelected(null)}>×</button></div><div className="metric-grid"><Metric label="페이스" value={fmtPace(selected.avgPaceSecPerKm)}/><Metric label="평균 심박" value={selected.avgHeartRate?Math.round(selected.avgHeartRate):'—'} unit={selected.avgHeartRate?'bpm':undefined}/><Metric label="최대 심박" value={selected.maxHeartRate?Math.round(selected.maxHeartRate):'—'} unit={selected.maxHeartRate?'bpm':undefined}/><Metric label="케이던스" value={selected.avgCadence?Math.round(selected.avgCadence):'—'} unit={selected.avgCadence?'spm':undefined}/><Metric label="칼로리" value={selected.calories?Math.round(selected.calories):'—'} unit={selected.calories?'kcal':undefined}/><Metric label="걸음수" value={selected.steps?Math.round(selected.steps).toLocaleString():'—'}/><Metric label="VO₂ Max" value={selected.vo2max??'—'}/><Metric label="고도 상승" value={selected.elevationGainM?selected.elevationGainM.toFixed(1):'—'} unit={selected.elevationGainM?'m':undefined}/></div><div className="modal-actions"><button className="danger" onClick={()=>setConfirm({kind:'trash',id:selected.id})}>휴지통으로 이동</button><button className="primary" onClick={()=>setSelected(null)}>닫기</button></div></div></div>}
  {confirm&&<div className="modal-backdrop"><div className="modal confirm"><div className="eyebrow">CONFIRM</div><h2>{confirm.kind==='trash'?'기록을 휴지통으로 이동할까요?':confirm.kind==='restore'?'기록을 복원할까요?':'영구 삭제할까요?'}</h2><p>{confirm.kind==='delete'?'영구 삭제한 기록은 이 브라우저에서 복구할 수 없습니다.':'휴지통에서는 언제든 복원할 수 있습니다.'}</p><div className="modal-actions"><button className="secondary" onClick={()=>setConfirm(null)}>취소</button><button className={confirm.kind==='delete'?'danger':'primary'} onClick={applyConfirm}>{confirm.kind==='trash'?'이동':confirm.kind==='restore'?'복원':'삭제'}</button></div></div></div>}
 </main>;
}