'use client';

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';

type ActivityType = '러닝' | '걷기' | '자전거' | '등산' | '기타';
type Tab = 'dashboard' | 'records' | 'analysis' | 'more';
type Lap = { lap:number; distanceKm:number; durationSec:number; paceSecPerKm:number };
type HrZone = { zone:string; range:string; seconds:number; percent:number };
type Dynamics = { balance?:string; groundContactMs?:number; flightMs?:number; regularity?:string; verticalOscillationCm?:number; stiffness?:number };

type Activity = {
  id:string; date:string; type:ActivityType; distanceKm:number; durationSec:number;
  calories?:number; steps?:number; avgPaceSecPerKm?:number; bestPaceSecPerKm?:number;
  avgSpeedKmh?:number; bestSpeedKmh?:number; elevationGainM?:number; elevationMinM?:number; elevationMaxM?:number;
  totalAscentKm?:number; totalDescentKm?:number; avgHeartRate?:number; maxHeartRate?:number;
  avgCadence?:number; maxCadence?:number; vo2max?:number; thresholdAerobicBpm?:number; thresholdAnaerobicBpm?:number;
  recoveryBpm?:number; laps?:Lap[]; hrZones?:HrZone[]; dynamics?:Dynamics; screenshotUrls?:string[]; screenshotNames?:string[];
  note?:string; source?:string;
};
type Draft = Omit<Activity,'id'>;

const KEY='motion-log-activities-v2';
const THEME='motion-log-theme-v2';
const seed:Activity[]=[
  {id:'demo1',date:'2026-09-12',type:'러닝',distanceKm:3.03,durationSec:1197,calories:314,steps:3205,avgPaceSecPerKm:394,bestPaceSecPerKm:323,avgSpeedKmh:9.1,bestSpeedKmh:11.1,elevationGainM:30,elevationMinM:39,elevationMaxM:71,totalAscentKm:.13,totalDescentKm:.12,avgHeartRate:161,maxHeartRate:177,avgCadence:160,maxCadence:174,vo2max:37.5,thresholdAerobicBpm:133,thresholdAnaerobicBpm:171,hrZones:[{zone:'Z1',range:'92–133 bpm',seconds:58,percent:4.9},{zone:'Z2',range:'134–171 bpm',seconds:900,percent:75.5},{zone:'Z3',range:'172–185 bpm',seconds:39,percent:19.6}],laps:[{lap:1,distanceKm:1,durationSec:395,paceSecPerKm:395},{lap:2,distanceKm:1,durationSec:414,paceSecPerKm:414},{lap:3,distanceKm:1,durationSec:372,paceSecPerKm:372},{lap:4,distanceKm:.03,durationSec:15,paceSecPerKm:450}],dynamics:{balance:'매우 좋음',groundContactMs:171,flightMs:196,regularity:'매우 좋음',verticalOscillationCm:9.2,stiffness:53},source:'삼성헬스 예시'},
  {id:'demo2',date:'2026-09-15',type:'걷기',distanceKm:5,durationSec:3540,calories:305,avgPaceSecPerKm:708,avgHeartRate:118,avgCadence:122,note:'가볍게 회복',source:'예시 데이터'}
];
const blank:Draft={date:new Date().toISOString().slice(0,10),type:'러닝',distanceKm:0,durationSec:0,source:'삼성헬스 캡처',screenshotUrls:[],screenshotNames:[]};
const fmtDate=(d:string)=>{const x=new Date(`${d}T00:00:00`);return `${x.getMonth()+1}월 ${x.getDate()}일`};
const fmtClock=(s=0)=>{const n=Math.max(0,Math.round(s));const h=Math.floor(n/3600),m=Math.floor((n%3600)/60),r=n%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${m}:${String(r).padStart(2,'0')}`};
const fmtDur=(s=0)=>{const n=Math.max(0,Math.round(s));const h=Math.floor(n/3600),m=Math.floor((n%3600)/60),r=n%60;return h?`${h}시간 ${m}분`:`${m}분 ${String(r).padStart(2,'0')}초`};
const fmtPace=(s?:number)=>s?`${Math.floor(s/60)}'${String(Math.round(s%60)).padStart(2,'0')}"/km`:'—';
const avg=(v:number[])=>{const a=v.filter(Number.isFinite);return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0};

function Metric({label,value,unit}:{label:string;value:string|number;unit?:string}){return <div className="metric"><span>{label}</span><strong>{value}{unit&&<small>{unit}</small>}</strong></div>}
function Trend({values,unit=''}:{values:number[];unit?:string}){if(!values.length)return <div className="empty-chart">기록이 쌓이면 추세가 표시됩니다.</div>;const min=Math.min(...values),max=Math.max(...values),range=max-min||1;const pts=values.map((v,i)=>{const x=18+i*(464/Math.max(1,values.length-1));const y=118-((v-min)/range)*88;return [x,y]});return <div className="chart-box"><svg viewBox="0 0 500 140"><line x1="18" x2="482" y1="24" y2="24" className="chart-grid"/><line x1="18" x2="482" y1="71" y2="71" className="chart-grid"/><line x1="18" x2="482" y1="118" y2="118" className="chart-grid"/><polyline points={pts.map(p=>p.join(',')).join(' ')} fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round"/>{pts.map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r="4" fill="currentColor"/>)}</svg><div className="chart-caption"><span>{min}{unit}</span><b>{max}{unit}</b></div></div>}
function RecordCard({a,onOpen,onDelete}:{a:Activity;onOpen:()=>void;onDelete:()=>void}){return <article className="record-card" onClick={onOpen}><div className="record-date"><b>{fmtDate(a.date)}</b><span>{a.type}</span></div><div className="record-main"><b>{a.distanceKm.toFixed(2)}<small> km</small></b><span>{fmtDur(a.durationSec)} · {fmtPace(a.avgPaceSecPerKm)}</span></div><div className="record-tags">{a.avgHeartRate&&<span>♥ {a.avgHeartRate}</span>}{a.avgCadence&&<span>↟ {a.avgCadence}</span>}{a.calories&&<span>{a.calories} kcal</span>}{a.vo2max&&<span>VO₂ {a.vo2max}</span>}</div><button className="icon-button" onClick={e=>{e.stopPropagation();onDelete()}} aria-label="기록 삭제">×</button></article>}

export default function Home(){
  const [tab,setTab]=useState<Tab>('dashboard');
  const [acts,setActs]=useState<Activity[]>(seed);
  const [draft,setDraft]=useState<Draft>(blank);
  const [images,setImages]=useState<string[]>([]);
  const [names,setNames]=useState<string[]>([]);
  const [showImport,setShowImport]=useState(false);
  const [selected,setSelected]=useState<Activity|null>(null);
  const [msg,setMsg]=useState('');
  const [analyzing,setAnalyzing]=useState(false);
  const [dark,setDark]=useState(true);
  const [period,setPeriod]=useState<7|30|90>(30);

  useEffect(()=>{try{const a=localStorage.getItem(KEY);if(a)setActs(JSON.parse(a));const t=localStorage.getItem(THEME);if(t)setDark(t==='dark')}catch{}} ,[]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(acts))},[acts]);
  useEffect(()=>{localStorage.setItem(THEME,dark?'dark':'light')},[dark]);

  const sorted=useMemo(()=>[...acts].sort((a,b)=>b.date.localeCompare(a.date)),[acts]);
  const latest=sorted[0];
  const since=useMemo(()=>{const d=new Date();d.setDate(d.getDate()-(period-1));return d.toISOString().slice(0,10)},[period]);
  const periodActs=sorted.filter(a=>a.date>=since);
  const week=sorted.filter(a=>{const d=new Date();d.setDate(d.getDate()-6);return a.date>=d.toISOString().slice(0,10)});
  const weekDist=week.reduce((s,a)=>s+a.distanceKm,0),weekCal=week.reduce((s,a)=>s+(a.calories||0),0),weekHr=avg(week.map(a=>a.avgHeartRate||NaN));
  const latestVo2=sorted.find(a=>a.vo2max)?.vo2max;

  const open=()=>{setDraft({...blank,date:new Date().toISOString().slice(0,10)});setImages([]);setNames([]);setMsg('');setShowImport(true)};
  const files=(e:ChangeEvent<HTMLInputElement>)=>{const f=Array.from(e.target.files||[]).slice(0,3);if(!f.length)return;setNames(f.map(x=>x.name));Promise.all(f.map(x=>new Promise<string>((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=rej;r.readAsDataURL(x)}))).then(setImages).catch(()=>setMsg('이미지를 읽지 못했습니다.'))};
  const analyze=async()=>{if(!images.length){setMsg('삼성헬스 캡처를 먼저 선택해주세요.');return}setAnalyzing(true);setMsg('캡처의 화면과 숫자를 분석하고 있습니다…');try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({images})});const d=await r.json();if(!r.ok)throw new Error(d.error||'분석에 실패했습니다.');setDraft(p=>({...p,...d.activity,screenshotUrls:images,screenshotNames:names,source:'삼성헬스 캡처 + AI 분석'}));setMsg('분석 완료. 저장 전에 결과를 확인하세요.')}catch(e){setMsg(e instanceof Error?e.message:'분석에 실패했습니다.')}finally{setAnalyzing(false)}};
  const save=(e:FormEvent)=>{e.preventDefault();if(!draft.date||!draft.distanceKm||!draft.durationSec){setMsg('날짜, 거리, 운동 시간을 확인해주세요.');return}const a:Activity={...draft,id:crypto.randomUUID(),screenshotUrls:images,screenshotNames:names};setActs(p=>[a,...p]);setShowImport(false);setSelected(a);setTab('records');setMsg('운동 기록을 저장했습니다.')};
  const remove=(id:string)=>{setActs(p=>p.filter(a=>a.id!==id));if(selected?.id===id)setSelected(null)};
  const exportData=()=>{const b=new Blob([JSON.stringify(acts,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`motion-log-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u)};
  const importData=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result));if(!Array.isArray(p))throw new Error();setActs(p);setMsg('백업 데이터를 불러왔습니다.')}catch{setMsg('올바른 Motion Log 백업 파일이 아닙니다.')}};r.readAsText(f)};

  return <main className={dark?'app dark':'app'}>
    <aside className="sidebar"><div className="brand-line">GALAXY WATCH FITNESS LOG</div><nav>{([['dashboard','대시보드'],['records','운동 기록'],['analysis','분석'],['more','설정']] as const).map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav><div className="sidebar-foot"><button className="ghost" onClick={()=>setDark(v=>!v)}>{dark?'☼ 라이트 모드':'◐ 다크 모드'}</button><div className="small">Samsung Health 캡처 중심 기록</div></div></aside>
    <section className="content">
      <header className="topbar"><div><div className="eyebrow mobile-only">MOTION LOG</div><h1>{tab==='dashboard'?'오늘의 기록':tab==='records'?'운동 기록':tab==='analysis'?'분석':'설정'}</h1></div><button className="primary desktop-add" onClick={open}>+ 캡처로 기록</button><button className="mobile-add" onClick={open} aria-label="운동 캡처 추가">＋</button></header>
      {msg&&<button className="notice" onClick={()=>setMsg('')}>{msg}<span>×</span></button>}

      {tab==='dashboard'&&<>
        <section className="today-card"><div className="today-copy"><div className="eyebrow">TODAY · {new Date().toLocaleDateString('ko-KR')}</div>{latest?<><h2>{latest.type} <span>{latest.distanceKm.toFixed(2)} km</span></h2><p>{fmtDur(latest.durationSec)} · {fmtPace(latest.avgPaceSecPerKm)}{latest.avgHeartRate?` · 평균 ${latest.avgHeartRate} bpm`:''}</p></>:<><h2>아직 운동 기록이 없습니다.</h2><p>삼성헬스 캡처를 올려 첫 기록을 만들어보세요.</p></>}</div><button className="today-action" onClick={open}><span>＋</span><b>오늘 운동 기록</b><small>캡처 2장 기본 · 최대 3장</small></button></section>
        <section className="stats-grid"><Metric label="이번 주 운동" value={week.length} unit="회"/><Metric label="이번 주 거리" value={weekDist.toFixed(1)} unit="km"/><Metric label="이번 주 시간" value={fmtDur(week.reduce((s,a)=>s+a.durationSec,0))}/><Metric label="평균 심박" value={weekHr||'—'} unit={weekHr?'bpm':undefined}/><Metric label="칼로리" value={weekCal.toLocaleString()} unit="kcal"/><Metric label="VO₂ Max" value={latestVo2??'—'}/></section>
        <section className="section-head"><div><div className="eyebrow">QUICK VIEW</div><h3>바로가기</h3></div></section>
        <section className="nav-cards"><button onClick={()=>setTab('records')}><span className="nav-icon">◫</span><div><b>운동 기록</b><small>전체 운동과 상세 데이터</small></div><strong>→</strong></button><button onClick={()=>setTab('analysis')}><span className="nav-icon">⌁</span><div><b>분석</b><small>거리 · 심박 · VO₂ Max</small></div><strong>→</strong></button><button onClick={open}><span className="nav-icon">↥</span><div><b>캡처 추가</b><small>삼성헬스 사진 업로드</small></div><strong>→</strong></button></section>
        <section className="section-head"><div><div className="eyebrow">RECENT</div><h3>최근 운동</h3></div><button className="text-btn" onClick={()=>setTab('records')}>전체 보기 →</button></section>
        <div className="records-list">{sorted.slice(0,5).map(a=><RecordCard key={a.id} a={a} onOpen={()=>setSelected(a)} onDelete={()=>remove(a.id)}/>)}</div>
      </>}

      {tab==='records'&&<><section className="upload-card"><div className="upload-icon">↥</div><div><div className="eyebrow">IMPORT</div><h3>삼성헬스 캡처 2장으로 기록</h3><p>운동 상세정보 + 지도/차트를 기본으로 선택하세요. 구간기록은 필요할 때만 추가합니다.</p></div><button className="secondary" onClick={open}>사진 선택</button></section><div className="section-head"><div><div className="eyebrow">ALL RECORDS</div><h3>전체 운동</h3></div><span className="count-pill">{acts.length}개</span></div><div className="records-list">{sorted.map(a=><RecordCard key={a.id} a={a} onOpen={()=>setSelected(a)} onDelete={()=>remove(a.id)}/>)}</div></>}

      {tab==='analysis'&&<><div className="period-tabs">{([7,30,90] as const).map(p=><button key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p}일</button>)}</div><div className="analysis-grid"><section className="panel"><div className="eyebrow">DISTANCE</div><h3>운동 거리</h3><div className="big-number">{periodActs.reduce((s,a)=>s+a.distanceKm,0).toFixed(1)}<small>km</small></div><Trend values={[...periodActs].reverse().map(a=>Number(a.distanceKm.toFixed(2)))} unit="km"/></section><section className="panel"><div className="eyebrow">HEART RATE</div><h3>평균 심박</h3><div className="big-number">{avg(periodActs.map(a=>a.avgHeartRate||NaN))||'—'}<small>{avg(periodActs.map(a=>a.avgHeartRate||NaN))?'bpm':''}</small></div><Trend values={[...periodActs].reverse().filter(a=>a.avgHeartRate).map(a=>a.avgHeartRate as number)} unit="bpm"/></section><section className="panel"><div className="eyebrow">VO₂ MAX</div><h3>최대 산소 섭취량</h3><div className="big-number">{latestVo2??'—'}</div><Trend values={[...periodActs].reverse().filter(a=>a.vo2max).map(a=>a.vo2max as number)}/></section><section className="panel"><div className="eyebrow">SUMMARY</div><h3>운동량</h3><div className="analysis-summary"><div><span>운동</span><b>{periodActs.length}회</b></div><div><span>시간</span><b>{fmtDur(periodActs.reduce((s,a)=>s+a.durationSec,0))}</b></div><div><span>칼로리</span><b>{periodActs.reduce((s,a)=>s+(a.calories||0),0).toLocaleString()} kcal</b></div><div><span>종류</span><b>{new Set(periodActs.map(a=>a.type)).size}종류</b></div></div></section></div></>}

      {tab==='more'&&<><section className="panel settings-panel"><div className="eyebrow">DATA</div><h3>백업과 복원</h3><p>현재 브라우저에 저장된 운동 기록을 JSON 파일로 보관할 수 있습니다.</p><div className="settings-actions"><button className="secondary" onClick={exportData}>기록 내보내기</button><label className="secondary file-button">백업 불러오기<input type="file" accept="application/json" onChange={importData}/></label></div></section><section className="panel settings-panel"><div className="eyebrow">APP</div><h3>Motion Log</h3><p>Galaxy Watch → Samsung Health → 캡처 → Motion Log 흐름을 기준으로 만든 개인 운동 기록장입니다.</p></section></>}
    </section>

    <div className="bottom-nav">{([['dashboard','⌂','홈'],['records','◫','기록'],['analysis','⌁','분석'],['more','⋯','더보기']] as const).map(([k,i,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><span>{i}</span><small>{l}</small></button>)}</div>

    {showImport&&<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setShowImport(false)}}><form className="modal recorder" onSubmit={save}><div className="modal-head"><div><div className="eyebrow">IMPORT WORKOUT</div><h2>삼성헬스 캡처</h2><p>운동 상세 1장 + 지도/차트 1장을 기본으로 올리세요. 필요하면 구간기록 1장을 더할 수 있습니다.</p></div><button type="button" className="close" onClick={()=>setShowImport(false)}>×</button></div><label className="dropzone"><input type="file" accept="image/*" multiple onChange={files}/><strong>캡처 선택</strong><span>최대 3장 · 순서는 상관없음</span></label>{!!names.length&&<div className="file-list">{names.map((n,i)=><div className="file-row" key={`${n}-${i}`}><span>{i+1}</span><b>{n}</b><button type="button" onClick={()=>{setNames(v=>v.filter((_,j)=>j!==i));setImages(v=>v.filter((_,j)=>j!==i))}}>×</button></div>)}</div>}<div className="recorder-actions"><button type="button" className="secondary wide" onClick={analyze} disabled={analyzing||!images.length}>{analyzing?'분석 중…':'AI로 자동 읽기'}</button><span>분석 후 결과를 수정하고 저장할 수 있습니다.</span></div><div className="form-grid"><label>날짜<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>운동 종류<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as ActivityType})}><option>러닝</option><option>걷기</option><option>자전거</option><option>등산</option><option>기타</option></select></label><label>거리(km)<input type="number" step="0.01" value={draft.distanceKm||''} onChange={e=>setDraft({...draft,distanceKm:Number(e.target.value)})}/></label><label>운동 시간(초)<input type="number" value={draft.durationSec||''} onChange={e=>setDraft({...draft,durationSec:Number(e.target.value)})} placeholder="예: 1197"/></label><label>평균 심박<input inputMode="numeric" value={draft.avgHeartRate??''} onChange={e=>setDraft({...draft,avgHeartRate:Number(e.target.value)||undefined})}/></label><label>최대 심박<input inputMode="numeric" value={draft.maxHeartRate??''} onChange={e=>setDraft({...draft,maxHeartRate:Number(e.target.value)||undefined})}/></label><label>평균 케이던스<input inputMode="numeric" value={draft.avgCadence??''} onChange={e=>setDraft({...draft,avgCadence:Number(e.target.value)||undefined})}/></label><label>VO₂ Max<input type="number" step="0.1" value={draft.vo2max??''} onChange={e=>setDraft({...draft,vo2max:Number(e.target.value)||undefined})}/></label></div><label>메모<textarea value={draft.note||''} onChange={e=>setDraft({...draft,note:e.target.value})} placeholder="코스, 느낌, 통증, 신발 등을 기록"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setShowImport(false)}>취소</button><button className="primary" type="submit">기록 저장</button></div></form></div>}

    {selected&&<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><article className="modal detail"><div className="modal-head"><div><div className="eyebrow">WORKOUT DETAIL · {fmtDate(selected.date)}</div><h2>{selected.type} · {selected.distanceKm.toFixed(2)} km</h2><p>{fmtDur(selected.durationSec)} · {fmtPace(selected.avgPaceSecPerKm)}</p></div><button className="close" onClick={()=>setSelected(null)}>×</button></div><div className="metric-grid"><Metric label="평균 심박" value={selected.avgHeartRate??'—'} unit={selected.avgHeartRate?'bpm':undefined}/><Metric label="최대 심박" value={selected.maxHeartRate??'—'} unit={selected.maxHeartRate?'bpm':undefined}/><Metric label="평균 케이던스" value={selected.avgCadence??'—'} unit={selected.avgCadence?'spm':undefined}/><Metric label="VO₂ Max" value={selected.vo2max??'—'}/><Metric label="고도 상승" value={selected.elevationGainM??'—'} unit={selected.elevationGainM?'m':undefined}/><Metric label="칼로리" value={selected.calories??'—'} unit={selected.calories?'kcal':undefined}/></div>{selected.laps?.length?<section className="detail-section"><div className="eyebrow">LAPS</div><h3>구간 기록</h3><div className="lap-table"><div className="lap-row head"><span>구간</span><span>시간</span><span>거리</span><span>페이스</span></div>{selected.laps.map(l=><div className="lap-row" key={l.lap}><span>{l.lap}</span><span>{fmtClock(l.durationSec)}</span><span>{l.distanceKm.toFixed(2)} km</span><span>{fmtPace(l.paceSecPerKm)}</span></div>)}</div></section>:null}{selected.hrZones?.length?<section className="detail-section"><div className="eyebrow">HEART RATE ZONES</div><h3>심박 구간</h3><div className="zone-list">{selected.hrZones.map(z=><div className="zone-row" key={z.zone}><span>{z.zone}</span><div><b>{z.range}</b><small>{fmtDur(z.seconds)}</small></div><strong>{z.percent}%</strong></div>)}</div></section>:null}{selected.dynamics?<section className="detail-section"><div className="eyebrow">RUNNING DYNAMICS</div><h3>러닝 다이내믹</h3><div className="metric-grid compact"><Metric label="밸런스" value={selected.dynamics.balance??'—'}/><Metric label="지면 접촉" value={selected.dynamics.groundContactMs??'—'} unit="ms"/><Metric label="체공" value={selected.dynamics.flightMs??'—'} unit="ms"/><Metric label="규칙성" value={selected.dynamics.regularity??'—'}/><Metric label="수직 진폭" value={selected.dynamics.verticalOscillationCm??'—'} unit="cm"/><Metric label="강성" value={selected.dynamics.stiffness??'—'}/></div></section>:null}{selected.screenshotNames?.length?<section className="detail-section"><div className="eyebrow">SOURCE</div><h3>원본 캡처</h3><div className="saved-files">{selected.screenshotNames.map((n,i)=><div key={`${n}-${i}`}><span>{i+1}</span><b>{n}</b></div>)}</div></section>:null}{selected.note&&<section className="note-box">{selected.note}</section>}</article></div>}
  </main>
}
