'use client';

import { useEffect, useMemo, useState } from 'react';

type ActivityType = '러닝' | '걷기' | '자전거' | '등산' | '기타';
type Lap = { lap:number; distanceKm:number; durationSec:number; paceSecPerKm:number };
type HrZone = { zone:string; range:string; seconds:number; percent:number };
type Dynamics = { balance?:string; groundContactMs?:number; flightMs?:number; regularity?:string; verticalOscillationCm?:number; stiffness?:number };
type Activity = {
  id:string; date:string; type:ActivityType; distanceKm:number; durationSec:number;
  calories?:number; steps?:number; avgPaceSecPerKm?:number; bestPaceSecPerKm?:number; avgSpeedKmh?:number; bestSpeedKmh?:number;
  elevationGainM?:number; elevationMinM?:number; elevationMaxM?:number; totalAscentKm?:number; totalDescentKm?:number;
  avgHeartRate?:number; maxHeartRate?:number; avgCadence?:number; maxCadence?:number; vo2max?:number;
  thresholdAerobicBpm?:number; thresholdAnaerobicBpm?:number; recoveryBpm?:number; laps?:Lap[]; hrZones?:HrZone[]; dynamics?:Dynamics;
  source?:string; note?:string; deletedAt?:string;
};

type Tab='home'|'records'|'analysis'|'trash'|'more';

const seed:Activity[]=[
 {id:'demo1',date:'2026-09-12',type:'러닝',distanceKm:3.03,durationSec:1197,calories:314,steps:3205,avgPaceSecPerKm:394,bestPaceSecPerKm:323,avgSpeedKmh:9.1,bestSpeedKmh:11.1,elevationGainM:30,elevationMinM:39,elevationMaxM:71,totalAscentKm:.13,totalDescentKm:.12,avgHeartRate:161,maxHeartRate:177,avgCadence:160,maxCadence:174,vo2max:37.5,thresholdAerobicBpm:133,thresholdAnaerobicBpm:171,hrZones:[{zone:'Z1',range:'92–133 bpm',seconds:58,percent:4.9},{zone:'Z2',range:'134–171 bpm',seconds:900,percent:75.5},{zone:'Z3',range:'172–185 bpm',seconds:39,percent:19.6}],laps:[{lap:1,distanceKm:1,durationSec:395,paceSecPerKm:395},{lap:2,distanceKm:1,durationSec:414,paceSecPerKm:414},{lap:3,distanceKm:1,durationSec:372,paceSecPerKm:372},{lap:4,distanceKm:.03,durationSec:15,paceSecPerKm:450}],dynamics:{balance:'매우 좋음',groundContactMs:171,flightMs:196,regularity:'매우 좋음',verticalOscillationCm:9.2,stiffness:53},source:'삼성헬스 예시'},
 {id:'demo2',date:'2026-09-15',type:'걷기',distanceKm:5,durationSec:3540,calories:305,avgPaceSecPerKm:708,avgHeartRate:118,avgCadence:122,note:'가볍게 회복',source:'삼성헬스 예시'}
];

const STORAGE='motion-log-records-v3';
const THEME='motion-log-theme-v3';
const fmtDate=(d:string)=>{const x=new Date(`${d}T00:00:00`);return `${x.getMonth()+1}월 ${x.getDate()}일`};
const fmtDur=(s=0)=>{const n=Math.max(0,Math.round(s));const h=Math.floor(n/3600),m=Math.floor(n%3600/60),r=n%60;return h?`${h}시간 ${m}분`:`${m}분 ${String(r).padStart(2,'0')}초`};
const fmtPace=(s?:number)=>s?`${Math.floor(s/60)}'${String(Math.round(s%60)).padStart(2,'0')}"/km`:'—';
const avg=(v:number[])=>{const a=v.filter(Number.isFinite);return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0};
function Metric({label,value,unit}:{label:string;value:string|number;unit?:string}){return <div className="metric"><span>{label}</span><strong>{value}{unit&&<small>{unit}</small>}</strong></div>}
function RecordCard({a,onOpen,onTrash}:{a:Activity;onOpen:()=>void;onTrash:()=>void}){return <article className="record-card" onClick={onOpen}><div><div className="record-date"><b>{fmtDate(a.date)}</b><span>{a.type}</span></div><div className="record-main"><b>{a.distanceKm.toFixed(2)}<small> km</small></b><span>{fmtDur(a.durationSec)} · {fmtPace(a.avgPaceSecPerKm)}</span></div></div><div className="record-tags">{a.avgHeartRate&&<span>♥ {a.avgHeartRate}</span>}{a.avgCadence&&<span>↟ {a.avgCadence}</span>}{a.calories&&<span>{a.calories} kcal</span>}{a.vo2max&&<span>VO₂ {a.vo2max}</span>}</div><button className="icon-button" onClick={e=>{e.stopPropagation();onTrash()}}>×</button></article>}

export default function Home(){
 const [tab,setTab]=useState<Tab>('home');
 const [acts,setActs]=useState<Activity[]>([]);
 const [selected,setSelected]=useState<Activity|null>(null);
 const [confirm,setConfirm]=useState<{kind:'trash'|'restore'|'delete';id:string}|null>(null);
 const [dark,setDark]=useState(false);
 const [period,setPeriod]=useState<7|30|90>(30);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);setActs(raw?JSON.parse(raw):seed);const t=localStorage.getItem(THEME);if(t)setDark(t==='dark')}catch{setActs(seed)}},[]);
 useEffect(()=>{if(acts.length)localStorage.setItem(STORAGE,JSON.stringify(acts));localStorage.setItem(THEME,dark?'dark':'light')},[acts,dark]);
 const active=useMemo(()=>acts.filter(a=>!a.deletedAt).sort((a,b)=>b.date.localeCompare(a.date)),[acts]);
 const trash=useMemo(()=>acts.filter(a=>a.deletedAt).sort((a,b)=>String(b.deletedAt).localeCompare(String(a.deletedAt))),[acts]);
 const latest=active[0];
 const since=useMemo(()=>{const d=new Date();d.setDate(d.getDate()-(period-1));return d.toISOString().slice(0,10)},[period]);
 const scoped=active.filter(a=>a.date>=since);
 const week=active.filter(a=>{const d=new Date();d.setDate(d.getDate()-6);return a.date>=d.toISOString().slice(0,10)});
 const totalDist=week.reduce((s,a)=>s+a.distanceKm,0), totalTime=week.reduce((s,a)=>s+a.durationSec,0), totalCal=week.reduce((s,a)=>s+(a.calories||0),0), hr=avg(week.map(a=>a.avgHeartRate||NaN));
 const allDist=active.reduce((s,a)=>s+a.distanceKm,0);
 const trashTo=(id:string)=>setConfirm({kind:'trash',id});
 const restore=(id:string)=>setConfirm({kind:'restore',id});
 const permanent=(id:string)=>setConfirm({kind:'delete',id});
 const applyConfirm=()=>{if(!confirm)return;setActs(prev=>prev.map(a=>a.id===confirm.id?(confirm.kind==='trash'?{...a,deletedAt:new Date().toISOString()}:confirm.kind==='restore'?{...a,deletedAt:undefined}:null as any):a).filter(Boolean) as Activity[]);if(selected?.id===confirm.id)setSelected(null);setConfirm(null)};
 const title=tab==='home'?'운동 대시보드':tab==='records'?'운동 기록':tab==='analysis'?'분석':tab==='trash'?'휴지통':'설정';
 return <main className={dark?'app dark':'app'}>
  <aside className="sidebar"><div className="brand"><span>MOTION</span> LOG</div><div className="brand-sub">GALAXY WATCH FITNESS ARCHIVE</div><nav>{[['home','대시보드'],['records','운동 기록'],['analysis','분석'],['trash',`휴지통 ${trash.length?`(${trash.length})`:''}`],['more','설정']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as Tab)}>{l}</button>)}</nav><div className="sidebar-foot"><button className="ghost" onClick={()=>setDark(v=>!v)}>{dark?'☼ 라이트 모드':'◐ 다크 모드'}</button><small>삼성헬스 캡처 → ChatGPT 분석 → 기록 보관</small></div></aside>
  <section className="content"><header className="topbar"><div><div className="eyebrow">MOTION LOG</div><h1>{title}</h1></div><div className="status-pill">{active.length} RECORDS</div></header>
   {tab==='home'&&<><section className="hero"><div><div className="eyebrow">LATEST ACTIVITY</div>{latest?<><h2>{latest.type} <span>{latest.distanceKm.toFixed(2)} km</span></h2><p>{fmtDate(latest.date)} · {fmtDur(latest.durationSec)} · {fmtPace(latest.avgPaceSecPerKm)}{latest.avgHeartRate?` · 평균 ${latest.avgHeartRate} bpm`:''}</p></>:<><h2>운동 기록이 없습니다.</h2><p>프로젝트-운동에 삼성헬스 캡처를 올리면 기록이 추가됩니다.</p></>}</div><div className="workflow"><span>01</span><b>삼성헬스 캡처</b><span>02</span><b>ChatGPT 분석</b><span>03</span><b>웹 기록 반영</b></div></section><section className="stats-grid"><Metric label="이번 주 운동" value={week.length} unit="회"/><Metric label="이번 주 거리" value={totalDist.toFixed(1)} unit="km"/><Metric label="이번 주 시간" value={fmtDur(totalTime)}/><Metric label="평균 심박" value={hr||'—'} unit={hr?'bpm':undefined}/><Metric label="칼로리" value={totalCal.toLocaleString()} unit="kcal"/><Metric label="누적 거리" value={allDist.toFixed(1)} unit="km"/></section><div className="section-head"><div><div className="eyebrow">RECENT</div><h3>최근 운동</h3></div><button className="text-btn" onClick={()=>setTab('records')}>전체 보기 →</button></div><div className="records-list">{active.slice(0,5).map(a=><RecordCard key={a.id} a={a} onOpen={()=>setSelected(a)} onTrash={()=>trashTo(a.id)}/>)}</div></>}
   {tab==='records'&&<><div className="section-head"><div><div className="eyebrow">ARCHIVE</div><h3>전체 운동 기록</h3></div><span className="count-pill">총 {active.length}회 · {allDist.toFixed(1)} km</span></div><div className="records-list">{active.map(a=><RecordCard key={a.id} a={a} onOpen={()=>setSelected(a)} onTrash={()=>trashTo(a.id)}/>)}</div>{!active.length&&<div className="empty">아직 저장된 운동 기록이 없습니다.</div>}</>}
   {tab==='analysis'&&<><div className="period-tabs">{([7,30,90] as const).map(p=><button key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p}일</button>)}</div><section className="analysis-grid"><div className="panel"><div className="eyebrow">DISTANCE</div><div className="big-number">{scoped.reduce((s,a)=>s+a.distanceKm,0).toFixed(1)}<small> km</small></div><div className="bar-list">{scoped.slice(0,8).map((a,i)=><div key={a.id}><span>{fmtDate(a.date)}</span><i><em style={{width:`${Math.max(6,Math.min(100,a.distanceKm/10*100))}%`}}/></i><b>{a.distanceKm.toFixed(2)}</b></div>)}</div></div><div className="panel"><div className="eyebrow">HEART RATE</div><div className="big-number">{avg(scoped.map(a=>a.avgHeartRate||NaN))||'—'}<small> bpm</small></div><div className="mini-grid">{scoped.slice(0,6).map(a=><div key={a.id}><span>{fmtDate(a.date)}</span><b>{a.avgHeartRate||'—'}</b></div>)}</div></div><div className="panel"><div className="eyebrow">VO₂ MAX</div><div className="big-number">{scoped.find(a=>a.vo2max)?.vo2max??'—'}</div><div className="mini-grid">{scoped.filter(a=>a.vo2max).slice(0,6).map(a=><div key={a.id}><span>{fmtDate(a.date)}</span><b>{a.vo2max}</b></div>)}</div></div><div className="panel"><div className="eyebrow">ACTIVITY MIX</div><div className="mini-grid">{(['러닝','걷기','자전거','등산','기타'] as ActivityType[]).map(t=><div key={t}><span>{t}</span><b>{scoped.filter(a=>a.type===t).length}회</b></div>)}</div></div></section></>}
   {tab==='trash'&&<><div className="trash-note">휴지통으로 이동된 기록은 여기서 복원하거나 영구 삭제할 수 있습니다.</div><div className="records-list">{trash.map(a=><article className="trash-card" key={a.id}><div><b>{fmtDate(a.date)} · {a.type}</b><span>{a.distanceKm.toFixed(2)} km · {fmtDur(a.durationSec)}</span></div><div><button className="secondary" onClick={()=>restore(a.id)}>복원</button><button className="danger" onClick={()=>permanent(a.id)}>영구 삭제</button></div></article>)}</div>{!trash.length&&<div className="empty">휴지통이 비어 있습니다.</div>}</>}
   {tab==='more'&&<><section className="panel settings-panel"><div className="eyebrow">STORAGE</div><h3>기록 보관 방식</h3><p>운동 기록은 웹 표시용 데이터 구조로 관리합니다. 캡처 이미지는 웹 저장 데이터에 포함하지 않습니다.</p></section><section className="panel settings-panel"><div className="eyebrow">BACKUP</div><h3>브라우저 백업</h3><p>현재 기기에서 JSON으로 내보내거나 다시 불러올 수 있습니다.</p><div className="actions"><button className="secondary" onClick={()=>{const b=new Blob([JSON.stringify(acts,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='motion-log-backup.json';a.click();URL.revokeObjectURL(u)}}>JSON 내보내기</button><label className="secondary file-btn">JSON 불러오기<input type="file" accept="application/json" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result));if(!Array.isArray(p))throw 0;setActs(p);alert('불러오기를 완료했습니다.')}catch{alert('올바른 백업 파일이 아닙니다.')}};r.readAsText(f)}}/></label></div></section></>}
  </section>
  <nav className="bottom-nav">{[['home','⌂','홈'],['records','▤','기록'],['analysis','⌁','분석'],['trash','♜','휴지통'],['more','⋯','설정']].map(([k,ic,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as Tab)}><span>{ic}</span><small>{l}</small></button>)}</nav>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal detail" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">WORKOUT DETAIL</div><h2>{selected.type}</h2><p>{fmtDate(selected.date)} · {selected.source||'삼성헬스'}</p></div><button className="close" onClick={()=>setSelected(null)}>×</button></div><div className="metric-grid"><Metric label="거리" value={selected.distanceKm.toFixed(2)} unit="km"/><Metric label="운동시간" value={fmtDur(selected.durationSec)}/><Metric label="페이스" value={fmtPace(selected.avgPaceSecPerKm)}/><Metric label="평균 심박" value={selected.avgHeartRate||'—'} unit="bpm"/><Metric label="최대 심박" value={selected.maxHeartRate||'—'} unit="bpm"/><Metric label="케이던스" value={selected.avgCadence||'—'} unit="spm"/><Metric label="칼로리" value={selected.calories||'—'} unit="kcal"/><Metric label="VO₂ Max" value={selected.vo2max??'—'}/></div>{selected.laps?.length&&<div className="detail-section"><h3>랩</h3><div className="lap-table"><div className="lap-row head"><span>랩</span><span>거리</span><span>시간</span><span>페이스</span></div>{selected.laps.map(l=><div className="lap-row" key={l.lap}><span>{l.lap}</span><span>{l.distanceKm.toFixed(2)} km</span><span>{fmtDur(l.durationSec)}</span><span>{fmtPace(l.paceSecPerKm)}</span></div>)}</div></div>}{selected.hrZones?.length&&<div className="detail-section"><h3>심박 존</h3><div className="zone-list">{selected.hrZones.map(z=><div className="zone-row" key={z.zone}><b>{z.zone}</b><span>{z.range}</span><strong>{z.percent}%</strong></div>)}</div></div>}{selected.dynamics&&<div className="detail-section"><h3>러닝 다이내믹스</h3><div className="mini-grid">{Object.entries(selected.dynamics).map(([k,v])=><div key={k}><span>{k}</span><b>{String(v)}</b></div>)}</div></div>}<div className="detail-note">원본 캡처를 기준으로 읽을 수 있는 값만 기록합니다. 보이지 않는 값은 임의로 채우지 않습니다.</div></div></div>}
  {confirm&&<div className="modal-backdrop"><div className="modal confirm"><div className="eyebrow">CONFIRM</div><h2>{confirm.kind==='trash'?'휴지통으로 이동할까요?':confirm.kind==='restore'?'기록을 복원할까요?':'영구 삭제할까요?'}</h2><p>{confirm.kind==='delete'?'영구 삭제한 기록은 복원할 수 없습니다.':confirm.kind==='trash'?'실수로 삭제해도 휴지통에서 다시 복원할 수 있습니다.':'휴지통에서 다시 운동 기록으로 이동합니다.'}</p><div className="modal-actions"><button className="secondary" onClick={()=>setConfirm(null)}>취소</button><button className={confirm.kind==='delete'?'danger':'primary'} onClick={applyConfirm}>{confirm.kind==='trash'?'휴지통 이동':confirm.kind==='restore'?'복원':'영구 삭제'}</button></div></div></div>}
 </main>;
}
